### ISSUE TITLE
Not easy to use with Docker containers - feature request

### ISSUE THREAD

**Issue by bwims** [colinl/node-red-contrib-influxdb-backup#1]
Hello,

the only way I can think of to make this work would be to issue the influx commands via ssh to the influx container.

Is this possible, do you think?

There is no way I can install influx in the same container as node red.

**Comment by colinl** [comment]
Perhaps you could write a script in the node red container, with the same
name as influx, and in there pass the command on to wherever you have
installed influx.

**Comment by bwims** [comment]
Ah, now I understand - I should have looked at what your code does first!  I had not realised it was mainly spawning a command line.  I was fooled by the requirement to provide a port number.  I had imagined that influx provided some sort of api to kick off the backups via a sort of url, which would have worked, as I can easily write to the database.

Ok, never mind.  I don't think there is a solution.

Thanks!
